export const legalContact = { developer: "DraBornEagle", app: "DraBornSeries", email: "support@draborneagle.com", updated: "1 Ekim 2026", version: "2026-10-01-v072" };
export type LegalPage = "privacy" | "terms" | "delete-account";
export type LegalSection = { title: string; paragraphs: string[] };
export const legalDocuments: Record<LegalPage, { title: string; intro: string; updated?: string; sections: LegalSection[] }> = {
  privacy: {
    title: "Gizlilik Politikası",
    updated: "5 Ekim 2026 · v0.7.7.4",
    intro: "Bu politika DraBornEagle tarafından sunulan DraBornSeries v0.7.7.4 Android uygulaması ve web sitesi için geçerlidir. Hesap, izleme, ödeme ve isteğe bağlı özelliklerde verilerinin nasıl işlendiğini burada bulabilirsin.",
    sections: [
      { title: "Hesap ve profil", paragraphs: ["Kayıt olduğunda e-posta adresin, giriş kimliğin ve şifrenin kimlik doğrulama hizmetindeki korumalı kaydı işlenir. Kullanıcı adın, seçersen adın ve profil fotoğrafın hesabına bağlanır. Google ile girişte izin verdiğin e-posta adresi, ad ve Google profil fotoğrafı alınır. İlk kullanıcı adı e-posta adresinin @ işaretinden önceki kısmından oluşturulur; profilinden düzenleyebilirsin. Profil fotoğrafı isteğe bağlıdır; Google’dan alınan fotoğrafı kaldırabilir veya sistemin fotoğraf seçicisinden başka bir görsel seçebilirsin. Profil görselleri herkese açık bir bağlantıda saklanır; özel veya hassas bir görsel yüklememelisin."] },
      { title: "İzleme ve uygulama etkinliği", paragraphs: ["Favoriler, beğeniler, puanlar, izleme geçmişi ve ilerlemesi, kaydettiğin aramalar, dil ve bildirim tercihleri Android ve web arasında eşitlenir. BornCoins hareketleri, promosyon kullanımı, bölüm erişimleri ve varsa VIP durumu hizmeti sunmak ve hatalı kullanımı önlemek için tutulur. Yorumların ve destek bildirimlerin hesabınla ilişkilendirilir. Yeni yorumlar onaylı şekilde yayımlanır; bildirilen veya kurallara uymayan yorumlar moderasyon tarafından gizlenebilir."] },
      { title: "Cihaz, bağlantı ve yerel depolama", paragraphs: ["Oturum yönetimi için uygulamanın ürettiği rastgele cihaz kimliği, platform, oturum kimliği ve son kullanım zamanı işlenir. Sunucu ve video sağlayıcıları bağlantı sırasında IP adresi, tarayıcı/cihaz bilgisi ve teknik erişim kayıtlarını işleyebilir. Oturum, dil, cihaz kimliği, çevrimdışı bekleyen izleme ilerlemesi ve kayıt sırasında seçilen geçici profil fotoğrafı cihazın yerel depolamasında tutulabilir. IMEI, rehber, konum, mikrofon veya kamera verisi toplanmaz."] },
      { title: "Listem’de arama", paragraphs: ["Favorilerim ve İzleme geçmişi sekmelerindeki arama, hesabına ait mevcut listeyi cihazında filtreler. Bu arama kutularına yazdığın metin sunucuya gönderilmez ve kalıcı arama geçmişine eklenmez. Uygulamanın genel arama sayfasında kaydettiğin aramalar ise hesabınla ilişkilendirilebilir ve arama geçmişinden temizlenebilir."] },
      { title: "Amaçlar ve hizmet sağlayıcılar", paragraphs: ["Veriler giriş, profil, izleme senkronizasyonu, içerik erişimi, satın alma doğrulama, destek, yorum moderasyonu ve güvenlik için kullanılır. Hizmeti değerlendirmek için izlenme, beğeni ve kullanım istatistikleri hesaplanabilir. DraBornSeries kişisel verilerini satmaz.", "Kimlik doğrulama, veritabanı ve profil fotoğrafı depolama için Supabase; videolar ve altyazılar için Cloudflare R2 ve DraBornSeries Worker kullanılır. Katalogdaki kaynağına göre mevcut CloudFront veya Cloudflare Stream bağlantıları da kullanılabilir. Google ile giriş seçildiğinde Google’ın kimlik doğrulama hizmeti kullanılır. Bu sağlayıcılar verileri kendi altyapılarında, Türkiye dışında da işleyebilir. Dış bağlantıyı veya paylaşım özelliğini kullandığında gittiğin hizmetin gizlilik kuralları da geçerlidir."] },
      { title: "Android reklamları ve gizlilik tercihleri", paragraphs: ["Web sürümünde AdMob reklamı gösterilmez. v0.7.7.4 Android sürümünde Google AdMob SDK’sı örnek reklamlarla çalışır. Örnek reklamlar gerçek BornCoins veya bölüm erişimi kazandırmaz. Reklam SDK’sı IP adresi, cihaz ve uygulama bilgileri, uygulama kümesi kimliği gibi SDK tanımlayıcıları, reklam etkileşimleri ve tanılama verilerini reklam sunumu, ölçüm ve kötüye kullanım önleme amacıyla işleyebilir. IP adresinden yaklaşık bölge çıkarılabilir; uygulama cihazın GPS konumunu istemez.", "Android reklam kimliği izni kapalıdır ve kişiselleştirilmiş reklam istenmez. Bu, reklam SDK’sının bağlantı ve tanılama verisi işlemesini tamamen durdurduğu anlamına gelmez. Gerçek reklamlar etkinleştirildiğinde Google’ın rıza yönetimi ekranı uygulanır; gerekli gizlilik tercihleri tamamlanmadan reklam istenmez. Uygun olduğunda Ayarlar’daki Reklam gizlilik tercihleri üzerinden seçimini yeniden açabilirsin."] },
      { title: "Google Play ödemeleri ve üyelik", paragraphs: ["VIP abonelikleri ve tek seferlik BornCoins paketleri Android’de Google Play ödeme ekranında satın alınır. Webdeki abonelik ve ödeme düğmeleri DraBornSeries’in Google Play mağaza sayfasını açar; web sitesi kart bilgisi almaz. Doğrulanmış VIP erişimi ve BornCoins bakiyesi aynı DraBornSeries hesabıyla Android ve webde geçerlidir.", "Satın alma token’ı, ürün ve sipariş kimliği, abonelik dönemi, yenilenme, iptal, bekleyen ödeme, sona erme ve iade durumu sunucuda Google Play ile doğrulanır. Makbuzlar aynı satın alımın yeniden bakiye veya erişim vermesini önlemek ve geri yükleme yapmak için hesabınla eşleştirilir. Kart veya banka bilgilerin DraBornSeries’e aktarılmaz. Play ödeme hesabının veri kullanımı Google’ın kendi gizlilik kurallarına tabidir. Hesabını silmek abonelik yenilenmesini iptal etmez; yenilemeyi Google Play aboneliklerinden ayrıca kapatabilirsin."] },
      { title: "Bildirimler", paragraphs: ["Yeni bölüm bildirim tercihin ve uygulama içi bildirim kayıtları hesabınla ilişkilendirilir. Bu sürümde Android uzaktan push gönderimi etkin değildir ve push cihaz token’ı kaydedilmez. Giriş, e-posta doğrulama ve şifre sıfırlama işlemleri için kayıtlı e-posta adresin kullanılır."] },
      { title: "Otomatik altyazı", paragraphs: ["Stüdyo üzerinden eklenen R2 videolarının sesleri Türkçe altyazı oluşturmak için otomatik çözümlenebilir. İşlem GitHub Actions üzerinde Whisper ve gerektiğinde İngilizceden Türkçeye çeviri modeliyle yapılır. İşlem yalnızca yayıncının eklediği video dosyalarını kullanır; izleyicinin mikrofonu kaydedilmez. Geçici video ve ses dosyaları işlem ortamı kapandığında kaldırılır; üretilen altyazılar bölümün erişim kurallarına uygun bağlantılarla sunulur. Otomatik altyazıda yazım, anlam veya zamanlama hataları olabilir; bunları Yardım ve destek bölümünden bildirebilirsin."] },
      { title: "Güvenlik ve saklama", paragraphs: ["Uygulamanın sunucu istekleri HTTPS üzerinden yapılır. Hesap verilerine erişim oturum ve sahiplik kontrolleriyle sınırlandırılır. Profil ve hizmet verileri hesabın açık olduğu sürece saklanır; yorumlarını, arama geçmişini ve profil fotoğrafını ayrıca silebilirsin.", "Hesap silindiğinde DraBornSeries’e ait profil alanları temizlenir; izleme, favori, yorum, cihaz/oturum ve cüzdan kayıtları silinir. Hesabın eski oturumlarla yeniden etkinleşmesini engelleyen asgari kimlik eşlemesi ve silindi işareti güvenlik amacıyla korunur. DraBornEagle’ın ortak giriş kimliği (e-posta ve kimlik doğrulama kaydı) diğer uygulamalara girişini bozmamak için korunur. Ortak giriş hesabının da silinmesini istersen destek adresinden ayrıca talep edebilirsin.", "Hizmet sağlayıcının yedeklerinde bulunan kopyalar yedek saklama döngüsünün sonunda kaldırılır; yedek süresinin ve teknik erişim kayıtlarının güncel ayrıntılarını destek adresinden isteyebilirsin. Güvenlik, kötüye kullanım veya yürürlükteki yükümlülük nedeniyle tutulması gereken kayıtlar kullanım amacıyla sınırlı tutulur."] },
      { title: "Tercihlerin ve hakların", paragraphs: ["Profil → Hesap ayarları içinden bilgilerini düzenleyebilir, fotoğrafını kaldırabilir, oturumlarını yönetebilir ve DraBornSeries hesabını silebilirsin. Uygulamayı yeniden kurmadan web hesap silme sayfasını da kullanabilirsin. Verilerine erişim, düzeltme, kopya alma veya silme talebini support@draborneagle.com adresine iletebilirsin; hesabın sana ait olduğunu doğrulamanı isteyebiliriz. Şifreni göndermemelisin."] },
      { title: "Çocuklar ve değişiklikler", paragraphs: ["DraBornSeries çocuklara özel tasarlanmış bir hizmet değildir. İçerik yaş rozetleri film bilgisi içindir; uygulamanın mağaza yaş derecelendirmesi ayrıca belirlenir. Bir çocuğa ait verinin uygunsuz işlendiğini düşünüyorsan destek adresine bildir. Veri kullanımı değiştiğinde politika tarihi güncellenir ve gerekli durumlarda uygulamada bilgilendirme yapılır."] },
      { title: "İletişim", paragraphs: ["Uygulama: DraBornSeries. Geliştirici: DraBornEagle. Gizlilik ve destek: support@draborneagle.com."] },
    ],
  },
  terms: {
    title: "Kullanım Koşulları ve Topluluk Kuralları",
    intro: "Hikâyeleri izlerken ve yorum paylaşırken herkes için güvenli ve saygılı bir alan oluşturalım.",
    sections: [
      { title: "Hizmet ve hesabın", paragraphs: ["DraBornSeries hesabını yalnızca sana ait bilgilerle oluştur. Şifreni ve oturumunu paylaşma. İçeriğin erişim türü bölüm sayfasında gösterilir. VIP abonelikleri Google Play Android uygulamasından, Play Console ürünleri etkinleştirildiğinde satın alınabilir. Fiyat ve dönem mağaza onay ekranında gösterilir. Ücretli abonelikler iptal edilene kadar yenilenir; Google Play aboneliklerinden yenilemeyi iptal edebilir ve satın alımlarını geri yükleyebilirsin. Promosyon VIP süreleri otomatik yenilenmez. BornCoins nakit değeri taşımaz; BornCoins paketleri Google Play üzerinden tek seferlik ödeme ile alınır ve otomatik yenilenmez. Paket ve bonus toplamı onay öncesinde gösterilir; doğrulanmış bakiye aynı hesapla Android ve webde kullanılabilir."] },
      { title: "Promosyon kodları", paragraphs: ["Geçerli bir promosyon kodu BornCoins, belirlenen gün kadar VIP veya ikisini birlikte verebilir. Ödül miktarı, kullanım sınırı ve son geçerlilik tarihi kampanyaya göre belirlenir. Aynı kod her hesapta bir kez kullanılabilir. VIP süresi varsa mevcut geçerli VIP sürenin sonuna eklenir; otomatik yenilenen bir ücretli abonelik oluşturulmaz. BornCoins nakit karşılığı taşımaz. Süresi dolmuş, kapatılmış veya toplam kullanım sınırına ulaşmış kodlar kullanılamaz."] },
      { title: "Yorum ve profil kuralları", paragraphs: ["Yorumların ve profil görsellerin için gerekli haklara sahip olmalısın. Taciz, nefret söylemi, tehdit, çocukların istismarı, cinsel içerik, yasa dışı eylem teşviki, kişisel veri ifşası, kimliğe bürünme ve spam yasaktır. Hikâyenin sürprizlerini içeren yorumları spoiler olarak işaretle. Bu kurallara uymayan içerikler kaldırılabilir; tekrarlanan kötüye kullanımda DraBornSeries hesabına erişim kısıtlanabilir."] },
      { title: "Moderasyon, bildirme ve engelleme", paragraphs: ["Yeni yorumlar varsayılan olarak onaylı şekilde hemen yayımlanır. Bildirilen veya kurallara uymayan yorumlar moderasyon tarafından gizlenebilir. Yorum üzerindeki Şikayet et düğmesiyle içeriği bildirebilir, Kullanıcıyı engelle düğmesiyle o kişinin yorumlarını gizleyebilirsin. Kendi yorumunu silebilirsin. İçerik veya hak ihlallerini Yardım ve destek bölümünden ya da support@draborneagle.com adresinden bildirebilirsin."] },
      { title: "İçerik ve lisanslar", paragraphs: ["Açık lisanslı film sayfalarında özgün yapım ekibi, kaynak bağlantısı, lisans ve yapılan uyarlamalar gösterilir. Filmler DraBornSeries’in özgün yapımı olarak sunulmaz. Yeniden kullanım için ilgili filmin lisans koşullarını incele; uygulamanın arayüzü ve markası ayrı haklara tabidir."] },
      { title: "Gizlilik ve hesabını kapatma", paragraphs: ["Veri kullanımları Gizlilik Politikası’nda açıklanır. DraBornSeries hesabını uygulama ayarlarından veya web hesap silme sayfasından kapatabilirsin. Bu işlem uygulamaya ait verileri temizler; diğer DraBornEagle hizmetlerine ait veriler ayrıca talep edilmedikçe etkilenmez."] },
    ],
  },
  "delete-account": {
    title: "DraBornSeries Hesap Silme",
    intro: "DraBornSeries hesabını ve uygulamaya ait verilerini Android’den veya bu web sayfasından silebilirsin. Uygulamayı yeniden indirmen gerekmez.",
    sections: [
      { title: "Uygulama veya web hesabından sil", paragraphs: ["Giriş yapmışsan bu sayfadaki Hesabı kalıcı sil düğmesini kullan. Android’de Profil → Hesap ayarları → DraBornSeries hesabını sil yolunu da izleyebilirsin. SİL yazarak onay verdiğinde işlem sunucuda uygulanır ve bu cihazdaki oturum kapanır. İşlem geri alınamaz."] },
      { title: "Giriş yapamıyorsan silme talebi gönder", paragraphs: ["support@draborneagle.com adresine, kayıtlı e-posta adresinden, konusu DraBornSeries hesap silme talebi olan bir e-posta gönder. Yalnızca DraBornSeries verilerinin mi yoksa ortak DraBornEagle giriş hesabının da mı silinmesini istediğini belirt. Şifre veya ödeme bilgisi gönderme. Hesap sahipliği doğrulanır; işlem tamamlandığında aynı adres üzerinden bilgilendirilirsin."] },
      { title: "Silinen veriler", paragraphs: ["DraBornSeries profil alanları ve fotoğrafı, favoriler, beğeniler, puanlar, yorumlar, aramalar, izleme geçmişi ve ilerlemesi, BornCoins cüzdanı/hareketleri, bölüm erişimleri, bildirim tercihleri ve uygulama cihaz/oturum kayıtları temizlenir."] },
      { title: "Korunan asgari kayıtlar", paragraphs: ["Eski oturumlarla hesabın yeniden açılmasını engelleyen kimlik eşlemesi ve silindi işareti güvenlik amacıyla korunur. Hesap silme, Google Play aboneliğinin otomatik yenilenmesini iptal etmez; Google Play Abonelikler sayfasından ayrıca iptal etmelisin. Ortak giriş hesabı ve diğer DraBornEagle uygulamalarının verileri bu işlemden etkilenmez; ortak giriş hesabını ayrıca destek üzerinden silebilirsin. Teknik kayıtlar ve yedek kopyalar için Gizlilik Politikası’nın saklama açıklaması geçerlidir."] },
    ],
  },
};
export function deletionMailto() {
  return `mailto:${legalContact.email}?subject=${encodeURIComponent("DraBornSeries hesap silme talebi")}&body=${encodeURIComponent("DraBornSeries hesabımın ve uygulamaya ait verilerimin silinmesini istiyorum.\nKayıtlı e-posta adresim: \nSilme kapsamı: DraBornSeries\n\nŞifre eklemeyin.")}`;
}
