export const legalContact = { developer: "DraBornEagle", app: "DraBornSeries", email: "support@draborneagle.com", updated: "1 Ekim 2026", version: "2026-10-01-v072" };
export type LegalPage = "privacy" | "terms" | "delete-account";
export type LegalSection = { title: string; paragraphs: string[] };
export const legalDocuments: Record<LegalPage, { title: string; intro: string; sections: LegalSection[] }> = {
  privacy: {
    title: "Gizlilik Politikası",
    intro: "DraBornEagle tarafından sunulan DraBornSeries’in Android uygulamasında ve web sitesinde verilerinin nasıl kullanıldığını burada bulabilirsin.",
    sections: [
      { title: "Hesap ve profil", paragraphs: ["Kayıt olduğunda e-posta adresin, giriş kimliğin ve şifrenin kimlik doğrulama hizmetindeki korumalı kaydı işlenir. Kullanıcı adın, seçersen adın ve profil fotoğrafın hesabına bağlanır. Google ile girişte izin verdiğin e-posta adresi, ad ve Google profil fotoğrafı alınır. İlk kullanıcı adı e-posta adresinin @ işaretinden önceki kısmından oluşturulur; profilinden düzenleyebilirsin. Profil fotoğrafı isteğe bağlıdır; Google’dan alınan fotoğrafı kaldırabilir veya sistemin fotoğraf seçicisinden başka bir görsel seçebilirsin. Profil görselleri herkese açık bir bağlantıda saklanır; özel veya hassas bir görsel yüklememelisin."] },
      { title: "İzleme ve uygulama etkinliği", paragraphs: ["Favoriler, beğeniler, puanlar, izleme geçmişi ve ilerlemesi, kaydettiğin aramalar, dil ve bildirim tercihleri Android ve web arasında eşitlenir. BornCoins hareketleri, promosyon kullanımı, bölüm erişimleri ve varsa VIP durumu hizmeti sunmak ve hatalı kullanımı önlemek için tutulur. Yorumların ve destek bildirimlerin hesabınla ilişkilendirilir. Yeni yorumlar onaylı şekilde yayımlanır; bildirilen veya kurallara uymayan yorumlar moderasyon tarafından gizlenebilir."] },
      { title: "Cihaz, bağlantı ve yerel depolama", paragraphs: ["Oturum yönetimi için uygulamanın ürettiği rastgele cihaz kimliği, platform, oturum kimliği ve son kullanım zamanı işlenir. Sunucu ve video sağlayıcıları bağlantı sırasında IP adresi, tarayıcı/cihaz bilgisi ve teknik erişim kayıtlarını işleyebilir. Oturum, dil, cihaz kimliği, çevrimdışı bekleyen izleme ilerlemesi ve kayıt sırasında seçilen geçici profil fotoğrafı cihazın yerel depolamasında tutulabilir. IMEI, rehber, konum, mikrofon veya kamera verisi toplanmaz."] },
      { title: "Amaçlar ve hizmet sağlayıcılar", paragraphs: ["Veriler giriş, profil, izleme senkronizasyonu, içerik erişimi, destek, yorum moderasyonu ve güvenlik için kullanılır. Kimlik doğrulama, veritabanı ve fotoğraf depolama için Supabase kullanılır. Bu sürümün lisanslı test videoları CloudFront üzerinden sunulur; yeni videolar Cloudflare R2’de saklanır ve DraBornSeries Worker üzerinden sunulur. Mevcut Cloudflare Stream bağlantıları desteklenmeye devam eder. Google ile giriş seçildiğinde Google’ın kimlik doğrulama hizmeti de kullanılır. Bu hizmetler verileri kendi altyapılarında, ülkenin dışında da işleyebilir. Bir bağlantıyı paylaşman veya dış siteye gitmen halinde seçtiğin hizmetin gizlilik kuralları uygulanır.", "DraBornSeries kişisel verilerini satmaz. v0.7.4 özel Android derlemesinde Google AdMob reklam SDK’sı örnek reklamlarla çalışır. SDK, reklam isteği sırasında IP adresi, cihaz/uygulama bilgileri ve reklam etkileşimlerini işleyebilir. Reklam kimliği izni kapalıdır ve kişiselleştirilmiş reklam istenmez. Gerçek reklam birimleri etkinleştirildiğinde Google’ın rıza yönetimi ekranı uygulanır; gerekli bölgelerde tercihler tamamlanmadan reklam gösterilmez. Uygun olduğunda Ayarlar’dan reklam gizlilik tercihlerini yeniden açabilirsin. Test reklamları gerçek BornCoins veya bölüm erişimi kazandırmaz. Google Play VIP satın alımları, harici mağaza bağlantısı tamamlandığında açılır; satın alma kimliği ve sipariş/abonelik durumu sunucuda doğrulanır. Kart bilgilerin DraBornSeries’e aktarılmaz. Push bildirimleri henüz etkin değildir."] },
      { title: "Otomatik altyazı", paragraphs: ["Stüdyo üzerinden eklenen R2 videolarının sesleri Türkçe altyazı oluşturmak için otomatik çözümlenebilir. İşlem GitHub Actions üzerinde Whisper ve gerektiğinde İngilizceden Türkçeye çeviri modeliyle yapılır. İşlem yalnızca yayıncının eklediği video dosyalarını kullanır; izleyicinin mikrofonu kaydedilmez. Geçici video ve ses dosyaları işlem ortamı kapandığında kaldırılır; üretilen altyazılar bölümün erişim kurallarına uygun bağlantılarla sunulur. Otomatik altyazıda yazım, anlam veya zamanlama hataları olabilir; bunları Yardım ve destek bölümünden bildirebilirsin."] },
      { title: "Güvenlik ve saklama", paragraphs: ["Uygulamanın sunucu istekleri HTTPS üzerinden yapılır. Hesap verilerine erişim oturum ve sahiplik kontrolleriyle sınırlandırılır. Profil ve hizmet verileri hesabın açık olduğu sürece saklanır; yorumlarını, arama geçmişini ve profil fotoğrafını ayrıca silebilirsin.", "Hesap silindiğinde DraBornSeries’e ait profil alanları temizlenir; izleme, favori, yorum, cihaz/oturum ve cüzdan kayıtları silinir. Hesabın eski oturumlarla yeniden etkinleşmesini engelleyen asgari kimlik eşlemesi ve silindi işareti güvenlik amacıyla korunur. DraBornEagle’ın ortak giriş kimliği (e-posta ve kimlik doğrulama kaydı) diğer uygulamalara girişini bozmamak için korunur. Ortak giriş hesabının da silinmesini istersen destek adresinden ayrıca talep edebilirsin.", "Hizmet sağlayıcının yedeklerinde bulunan kopyalar yedek saklama döngüsünün sonunda kaldırılır; yedek süresinin ve teknik erişim kayıtlarının güncel ayrıntılarını destek adresinden isteyebilirsin. Güvenlik, kötüye kullanım veya yürürlükteki yükümlülük nedeniyle tutulması gereken kayıtlar kullanım amacıyla sınırlı tutulur."] },
      { title: "Tercihlerin ve hakların", paragraphs: ["Profil → Hesap ayarları içinden bilgilerini düzenleyebilir, fotoğrafını kaldırabilir, oturumlarını yönetebilir ve DraBornSeries hesabını silebilirsin. Uygulamayı yeniden kurmadan web hesap silme sayfasını da kullanabilirsin. Verilerine erişim, düzeltme, kopya alma veya silme talebini support@draborneagle.com adresine iletebilirsin; hesabın sana ait olduğunu doğrulamanı isteyebiliriz. Şifreni göndermemelisin."] },
      { title: "Çocuklar ve değişiklikler", paragraphs: ["DraBornSeries çocuklara özel tasarlanmış bir hizmet değildir. İçerik yaş rozetleri film bilgisi içindir; uygulamanın mağaza yaş derecelendirmesi ayrıca belirlenir. Bir çocuğa ait verinin uygunsuz işlendiğini düşünüyorsan destek adresine bildir. Veri kullanımı değiştiğinde politika tarihi güncellenir ve gerekli durumlarda uygulamada bilgilendirme yapılır."] },
      { title: "İletişim", paragraphs: ["Uygulama: DraBornSeries. Geliştirici: DraBornEagle. Gizlilik ve destek: support@draborneagle.com."] },
    ],
  },
  terms: {
    title: "Kullanım Koşulları ve Topluluk Kuralları",
    intro: "Hikâyeleri izlerken ve yorum paylaşırken herkes için güvenli ve saygılı bir alan oluşturalım.",
    sections: [
      { title: "Hizmet ve hesabın", paragraphs: ["DraBornSeries hesabını yalnızca sana ait bilgilerle oluştur. Şifreni ve oturumunu paylaşma. İçeriğin erişim türü bölüm sayfasında gösterilir. VIP abonelikleri Google Play Android uygulamasından, Play Console ürünleri etkinleştirildiğinde satın alınabilir. Fiyat ve dönem mağaza onay ekranında gösterilir. Ücretli abonelikler iptal edilene kadar yenilenir; Google Play aboneliklerinden yenilemeyi iptal edebilir ve satın alımlarını geri yükleyebilirsin. Promosyon VIP süreleri otomatik yenilenmez. BornCoins nakit değeri taşımaz; BornCoins paket satışı bu sürümde kapalıdır."] },
      { title: "Promosyon kodları", paragraphs: ["Geçerli bir promosyon kodu BornCoins, belirlenen gün kadar VIP veya ikisini birlikte verebilir. Ödül miktarı, kullanım sınırı ve son geçerlilik tarihi kampanyaya göre belirlenir. Aynı kod her hesapta bir kez kullanılabilir. VIP süresi varsa mevcut geçerli VIP sürenin sonuna eklenir; otomatik yenilenen bir ücretli abonelik oluşturulmaz. BornCoins nakit karşılığı taşımaz. Süresi dolmuş, kapatılmış veya toplam kullanım sınırına ulaşmış kodlar kullanılamaz."] },
      { title: "Yorum ve profil kuralları", paragraphs: ["Yorumların ve profil görsellerin için gerekli haklara sahip olmalısın. Taciz, nefret söylemi, tehdit, çocukların istismarı, cinsel içerik, yasa dışı eylem teşviki, kişisel veri ifşası, kimliğe bürünme ve spam yasaktır. Hikâyenin sürprizlerini içeren yorumları spoiler olarak işaretle. Bu kurallara uymayan içerikler kaldırılabilir; tekrarlanan kötüye kullanımda DraBornSeries hesabına erişim kısıtlanabilir."] },
      { title: "Moderasyon, bildirme ve engelleme", paragraphs: ["Yeni yorumlar varsayılan olarak onaylı şekilde hemen yayımlanır. Bildirilen veya kurallara uymayan yorumlar moderasyon tarafından gizlenebilir. Yorum üzerindeki Şikayet et düğmesiyle içeriği bildirebilir, Kullanıcıyı engelle düğmesiyle o kişinin yorumlarını gizleyebilirsin. Kendi yorumunu silebilirsin. İçerik veya hak ihlallerini Yardım ve destek bölümünden ya da support@draborneagle.com adresinden bildirebilirsin."] },
      { title: "İçerik ve lisanslar", paragraphs: ["Açık lisanslı film sayfalarında özgün yapım ekibi, kaynak bağlantısı, lisans ve yapılan uyarlamalar gösterilir. Filmler DraBornSeries’in özgün yapımı olarak sunulmaz. Yeniden kullanım için ilgili filmin lisans koşullarını incele; uygulamanın arayüzü ve markası ayrı haklara tabidir."] },
      { title: "Gizlilik ve hesabını kapatma", paragraphs: ["Veri kullanımları Gizlilik Politikası’nda açıklanır. DraBornSeries hesabını uygulama ayarlarından veya web hesap silme sayfasından kapatabilirsin. Bu işlem uygulamaya ait verileri temizler; diğer DraBornEagle hizmetlerine ait veriler ayrıca talep edilmedikçe etkilenmez."] },
    ],
  },
  "delete-account": {
    title: "DraBornSeries Hesap Silme",
    intro: "DraBornSeries hesabını ve uygulamaya ait verilerini Android’den veya bu web sayfasından silebilirsin. Uygulamayı yeniden indirmen gerekmez.",
    sections: [
      { title: "Uygulama veya web hesabından sil", paragraphs: ["Giriş yapmışsan bu sayfadaki Hesabı kalıcı sil düğmesini kullan. Android’de Profil → Hesap ayarları → DraBornSeries hesabını sil yolunu da izleyebilirsin. SİL yazarak onay verdiğinde işlem sunucuda uygulanır ve bu cihazdaki oturum kapanır. İşlem geri alınamaz."] },
      { title: "Giriş yapamıyorsan silme talebi gönder", paragraphs: ["support@draborneagle.com adresine, kayıtlı e-posta adresinden, konusu DraBornSeries hesap silme talebi olan bir e-posta gönder. Yalnızca DraBornSeries verilerinin mi yoksa ortak DraBornEagle giriş hesabının da mı silinmesini istediğini belirt. Şifre veya ödeme bilgisi gönderme. Hesap sahipliği doğrulanır; işlem tamamlandığında aynı adres üzerinden bilgilendirilirsin."] },
      { title: "Silinen veriler", paragraphs: ["DraBornSeries profil alanları ve fotoğrafı, favoriler, beğeniler, puanlar, yorumlar, aramalar, izleme geçmişi ve ilerlemesi, BornCoins cüzdanı/hareketleri, bölüm erişimleri, bildirim tercihleri ve uygulama cihaz/oturum kayıtları temizlenir."] },
      { title: "Korunan asgari kayıtlar", paragraphs: ["Eski oturumlarla hesabın yeniden açılmasını engelleyen kimlik eşlemesi ve silindi işareti güvenlik amacıyla korunur. Hesap silme, Google Play aboneliğinin otomatik yenilenmesini iptal etmez; Google Play Abonelikler sayfasından ayrıca iptal etmelisin. Ortak giriş hesabı ve diğer DraBornEagle uygulamalarının verileri bu işlemden etkilenmez; ortak giriş hesabını ayrıca destek üzerinden silebilirsin. Teknik kayıtlar ve yedek kopyalar için Gizlilik Politikası’nın saklama açıklaması geçerlidir."] },
    ],
  },
};
export function deletionMailto() {
  return `mailto:${legalContact.email}?subject=${encodeURIComponent("DraBornSeries hesap silme talebi")}&body=${encodeURIComponent("DraBornSeries hesabımın ve uygulamaya ait verilerimin silinmesini istiyorum.\nKayıtlı e-posta adresim: \nSilme kapsamı: DraBornSeries\n\nŞifre eklemeyin.")}`;
}
