import { writeFile } from "node:fs/promises";
const imported = await import("../packages/shared/legal.ts");
const { legalDocuments, legalContact, deletionMailto } = imported.default || imported;
const escape = (text) => String(text).replace(/[&<>"']/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[char]);
const paths = { privacy: "privacy.html", terms: "terms.html", "delete-account": "account-deletion.html" };
export async function writeLegalPages(output = "dist") {
  for (const [page, document] of Object.entries(legalDocuments)) {
    const deletion = page === "delete-account" ? `<section class="request"><h2>Hesap silme talebini başlat</h2><a class="action" href="${escape(deletionMailto())}">E-posta ile silme talebi gönder</a><a class="action secondary" href="./?page=delete-account">Giriş yaptığım web hesabından sil</a><p>E-posta uygulaman açılmıyorsa kayıtlı adresinden <a href="mailto:${legalContact.email}">${legalContact.email}</a> adresine “DraBornSeries hesap silme talebi” konulu e-posta gönder. Şifre gönderme.</p></section>` : "";
    await writeFile(`${output}/${paths[page]}`, `<!doctype html><html lang="tr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#09080f"><meta name="description" content="${escape(document.intro)}"><title>${escape(document.title)} · DraBornSeries</title><style>
      *{box-sizing:border-box}body{margin:0;background:#09080f;color:#f7f0ff;font:16px/1.75 system-ui,sans-serif}main{max-width:900px;margin:auto;padding:28px 20px 60px}a{color:#97e6dc}nav{display:flex;gap:16px;flex-wrap:wrap;margin:20px 0}header,section{border:1px solid #493155;border-radius:22px;padding:24px;margin:20px 0;background:#15101f}header{background:linear-gradient(130deg,#322144,#171022)}h1{font-size:clamp(27px,5vw,42px);line-height:1.2}h2{font-size:21px;color:#edb4dc}p{color:#ccc2d4}small{color:#b6a7c1}.request{border-color:#64bbae;background:#15242a}.action{display:inline-block;margin:8px 10px 8px 0;padding:13px 18px;border-radius:15px;background:linear-gradient(110deg,#d42c87,#993dcc);color:white;text-decoration:none;font-weight:700}.secondary{background:#342344}a:focus-visible{outline:3px solid #f2a5db;outline-offset:5px}
      </style></head><body><main><a href="./">← DraBornSeries’e dön</a><header><small>DRABORNSERIES · DRABORNEAGLE</small><h1>${escape(document.title)}</h1><p>${escape(document.intro)}</p><small>Güncelleme: ${escape(document.updated || legalContact.updated)}</small></header>${deletion}${document.sections.map((section) => `<section><h2>${escape(section.title)}</h2>${section.paragraphs.map((paragraph) => `<p>${escape(paragraph)}</p>`).join("")}</section>`).join("")}<nav>${Object.entries(paths).map(([key, path]) => `<a href="./${path}">${escape(legalDocuments[key].title)}</a>`).join("")}<a href="mailto:${legalContact.email}">Destek</a></nav><small>DraBornEagle · DraBornSeries</small></main></body></html>`);
  }
}
