-- DraBornSeries v0.2. Additive changes remain inside the Series schema.
alter table drabornseries.dbs_google_play_products
  add column title text,
  add column billing_period text check (billing_period in ('weekly','monthly','yearly')),
  add column bonus_coins integer not null default 0 check (bonus_coins>=0),
  add column sort_order integer not null default 0;

insert into drabornseries.dbs_google_play_products(id,kind,coins,active,title,bonus_coins,sort_order) values
 ('dbs_coins_50','coins',50,false,'50 BornCoins',0,10),
 ('dbs_coins_100','coins',110,false,'100 + 10 BornCoins',10,20),
 ('dbs_coins_250','coins',280,false,'250 + 30 BornCoins',30,30),
 ('dbs_coins_500','coins',580,false,'500 + 80 BornCoins',80,40),
 ('dbs_coins_1000','coins',1200,false,'1.000 + 200 BornCoins',200,50),
 ('dbs_coins_2500','coins',3100,false,'2.500 + 600 BornCoins',600,60)
 on conflict(id) do update set title=excluded.title,coins=excluded.coins,bonus_coins=excluded.bonus_coins,sort_order=excluded.sort_order;
insert into drabornseries.dbs_borncoins_products(id,coins,bonus,sort_order)
 select id,coins-bonus_coins,bonus_coins,sort_order from drabornseries.dbs_google_play_products where kind='coins'
 on conflict(id) do update set coins=excluded.coins,bonus=excluded.bonus,sort_order=excluded.sort_order;
insert into drabornseries.dbs_google_play_products(id,kind,coins,active,title,billing_period,sort_order) values
 ('dbs_vip_weekly','vip',0,false,'DraBornSeries Haftalık VIP','weekly',100),
 ('dbs_vip_monthly','vip',0,false,'DraBornSeries Aylık VIP','monthly',110),
 ('dbs_vip_yearly','vip',0,false,'DraBornSeries Yıllık VIP','yearly',120)
 on conflict(id) do update set title=excluded.title,billing_period=excluded.billing_period,sort_order=excluded.sort_order;

insert into drabornseries.dbs_tasks(id,name,name_en,description,data) values
 ('welcome','DraBornSeries’e hoş geldin','Welcome to DraBornSeries','E-posta hesabınla giriş yap; bir defalık karşılama ödülünü al.','{"coins":80,"kind":"welcome"}'),
 ('favorite','İlk hikâyeni listene ekle','Start your collection','Bir diziyi Listem’e ekle, sonra ödülünü al.','{"coins":10,"kind":"favorite"}'),
 ('profile','Profilini kişiselleştir','Make it yours','Ayarlar bölümünde adını veya profil fotoğrafını kaydet.','{"coins":10,"kind":"profile"}')
 on conflict(id) do update set name=excluded.name,name_en=excluded.name_en,description=excluded.description,data=excluded.data;

create function dbs_series_private.dbs_claim_task(task text) returns jsonb
 language plpgsql security definer set search_path='' as $$
declare definition drabornseries.dbs_tasks; amount integer;
begin
 if not dbs_series_private.dbs_active() then raise exception 'AUTH_REQUIRED'; end if;
 select * into definition from drabornseries.dbs_tasks t where t.id=task and t.active;
 if definition.id is null or task not in ('welcome','favorite','profile') then raise exception 'TASK_UNAVAILABLE'; end if;
 -- All concurrent claims by this account serialize before the claimed check.
 perform 1 from drabornseries.dbs_borncoins_wallet where user_id=auth.uid() for update;
 if exists(select 1 from drabornseries.dbs_user_tasks where user_id=auth.uid() and tasks_id=task and claimed_at is not null) then raise exception 'ALREADY_CLAIMED'; end if;
 if task='welcome' and not exists(select 1 from auth.users where id=auth.uid() and email_confirmed_at is not null) then raise exception 'EMAIL_UNCONFIRMED'; end if;
 if task='favorite' and not exists(select 1 from drabornseries.dbs_favorites where user_id=auth.uid()) then raise exception 'TASK_INCOMPLETE'; end if;
 if task='profile' and not exists(select 1 from drabornseries.dbs_profiles where user_id=auth.uid() and (length(trim(coalesce(full_name,'')))>=2 or coalesce(avatar_url,'') like 'https://%')) then raise exception 'TASK_INCOMPLETE'; end if;
 amount:=(definition.data->>'coins')::integer;
 if amount is null or amount<=0 or amount>1000 then raise exception 'TASK_UNAVAILABLE'; end if;
 perform dbs_series_private.dbs_ledger(auth.uid(),amount,'task','task:'||auth.uid()||':'||task,definition.name);
 insert into drabornseries.dbs_user_tasks(user_id,tasks_id,progress,claimed_at) values(auth.uid(),task,1,now())
 on conflict(user_id,tasks_id) do update set progress=1,claimed_at=excluded.claimed_at;
 return jsonb_build_object('coins',amount,'task',task);
end $$;
create function drabornseries.dbs_claim_task(task text) returns jsonb
 language sql security invoker set search_path='' as $$ select dbs_series_private.dbs_claim_task(task) $$;
revoke all on function dbs_series_private.dbs_claim_task(text) from public,anon,authenticated;
revoke all on function drabornseries.dbs_claim_task(text) from public,anon,authenticated;
grant execute on function dbs_series_private.dbs_claim_task(text) to authenticated,service_role;
grant execute on function drabornseries.dbs_claim_task(text) to authenticated,service_role;

-- Preserve historical unlock/ledger references; retire the landscape demos.
update drabornseries.dbs_series set status='archived',featured_order=null where slug in ('big-buck-bunny','sintel') and is_demo;
update drabornseries.dbs_episodes set status='archived' where series_id in (select id from drabornseries.dbs_series where slug in ('big-buck-bunny','sintel') and is_demo);
insert into drabornseries.dbs_app_settings(key,value,public) values('release','{"version":"0.2.0","stage":"expo_go_test","format":"vertical"}',true)
 on conflict(key) do update set value=excluded.value;

-- Vertical demo scenes. Public third-party samples, not protected production content.
insert into drabornseries.dbs_series(slug,title,short_description,description,genres,accent,poster_url,banner_url,license,status,is_demo,featured_order,total_episodes,average_duration,production_year,age_rating) values('sehir-isiklari','Şehir Işıkları','Geceyi aydınlatan küçük bir karşılaşma.','Geceyi aydınlatan küçük bir karşılaşma. Bu koleksiyondaki bölümler, 9:16 oynatıcı ve kaydırmalı keşfet deneyimi için lisanslı kısa demo sahneleridir; tamamlanmış bir dizi yapımı değildir.',array['Romantik','Dram']::text[],'#ef4795','https://images.pexels.com/videos/5909013/pexels-photo-5909013.jpeg?auto=compress&cs=tinysrgb&w=600','https://images.pexels.com/videos/5909013/pexels-photo-5909013.jpeg?auto=compress&cs=tinysrgb&w=600','Pexels License · pexels.com/license/ · Katerina Holmes','published',true,1,2,12,2026,'13+') on conflict(slug) do update set title=excluded.title,short_description=excluded.short_description,description=excluded.description,genres=excluded.genres,accent=excluded.accent,poster_url=excluded.poster_url,banner_url=excluded.banner_url,license=excluded.license,status=excluded.status,is_demo=excluded.is_demo,featured_order=excluded.featured_order,total_episodes=excluded.total_episodes,average_duration=excluded.average_duration,production_year=excluded.production_year,age_rating=excluded.age_rating;
insert into drabornseries.dbs_seasons(series_id,number,title) select id,1,'İlk bakış' from drabornseries.dbs_series where slug='sehir-isiklari' on conflict do nothing;
insert into drabornseries.dbs_episodes(series_id,season_id,number,title,description,duration_seconds,thumbnail_url,orientation,access_type,status) select s.id,se.id,1,'Şehir Işıkları · Bölüm 1','Lisanslı dikey demo sahnesi. Pexels License · pexels.com/license/ · Katerina Holmes',12,'https://images.pexels.com/videos/5909013/pexels-photo-5909013.jpeg?auto=compress&cs=tinysrgb&w=600','portrait','free','published' from drabornseries.dbs_series s join drabornseries.dbs_seasons se on se.series_id=s.id and se.number=1 where s.slug='sehir-isiklari' on conflict(series_id,number) do update set title=excluded.title,description=excluded.description,duration_seconds=excluded.duration_seconds,thumbnail_url=excluded.thumbnail_url,orientation=excluded.orientation,access_type=excluded.access_type,status=excluded.status;
insert into drabornseries.dbs_video_assets(episode_id,provider,demo_url,ready) select e.id,'demo','https://videos.pexels.com/video-files/5909013/5909013-hd_720_1280_24fps.mp4',true from drabornseries.dbs_episodes e join drabornseries.dbs_series s on s.id=e.series_id where s.slug='sehir-isiklari' and e.number=1 on conflict(episode_id) do update set provider=excluded.provider,demo_url=excluded.demo_url,ready=true;
insert into drabornseries.dbs_episodes(series_id,season_id,number,title,description,duration_seconds,thumbnail_url,orientation,access_type,status) select s.id,se.id,2,'Şehir Işıkları · Bölüm 2','Lisanslı dikey demo sahnesi. Pexels License · pexels.com/license/ · Katerina Holmes',11,'https://images.pexels.com/videos/5909000/pexels-photo-5909000.jpeg?auto=compress&cs=tinysrgb&w=600','portrait','free','published' from drabornseries.dbs_series s join drabornseries.dbs_seasons se on se.series_id=s.id and se.number=1 where s.slug='sehir-isiklari' on conflict(series_id,number) do update set title=excluded.title,description=excluded.description,duration_seconds=excluded.duration_seconds,thumbnail_url=excluded.thumbnail_url,orientation=excluded.orientation,access_type=excluded.access_type,status=excluded.status;
insert into drabornseries.dbs_video_assets(episode_id,provider,demo_url,ready) select e.id,'demo','https://videos.pexels.com/video-files/5909000/5909000-hd_720_1280_24fps.mp4',true from drabornseries.dbs_episodes e join drabornseries.dbs_series s on s.id=e.series_id where s.slug='sehir-isiklari' and e.number=2 on conflict(episode_id) do update set provider=excluded.provider,demo_url=excluded.demo_url,ready=true;
insert into drabornseries.dbs_series(slug,title,short_description,description,genres,accent,poster_url,banner_url,license,status,is_demo,featured_order,total_episodes,average_duration,production_year,age_rating) values('geceye-bir-soz','Geceye Bir Söz','Şehrin ritminde, sadece ikimize ait bir an.','Şehrin ritminde, sadece ikimize ait bir an. Bu koleksiyondaki bölümler, 9:16 oynatıcı ve kaydırmalı keşfet deneyimi için lisanslı kısa demo sahneleridir; tamamlanmış bir dizi yapımı değildir.',array['Romantik']::text[],'#a977ee','https://images.pexels.com/videos/5909001/pexels-photo-5909001.jpeg?auto=compress&cs=tinysrgb&w=600','https://images.pexels.com/videos/5909001/pexels-photo-5909001.jpeg?auto=compress&cs=tinysrgb&w=600','Pexels License · pexels.com/license/ · Katerina Holmes','published',true,2,2,12,2026,'13+') on conflict(slug) do update set title=excluded.title,short_description=excluded.short_description,description=excluded.description,genres=excluded.genres,accent=excluded.accent,poster_url=excluded.poster_url,banner_url=excluded.banner_url,license=excluded.license,status=excluded.status,is_demo=excluded.is_demo,featured_order=excluded.featured_order,total_episodes=excluded.total_episodes,average_duration=excluded.average_duration,production_year=excluded.production_year,age_rating=excluded.age_rating;
insert into drabornseries.dbs_seasons(series_id,number,title) select id,1,'İlk bakış' from drabornseries.dbs_series where slug='geceye-bir-soz' on conflict do nothing;
insert into drabornseries.dbs_episodes(series_id,season_id,number,title,description,duration_seconds,thumbnail_url,orientation,access_type,status) select s.id,se.id,1,'Geceye Bir Söz · Bölüm 1','Lisanslı dikey demo sahnesi. Pexels License · pexels.com/license/ · Katerina Holmes',11,'https://images.pexels.com/videos/5909001/pexels-photo-5909001.jpeg?auto=compress&cs=tinysrgb&w=600','portrait','free','published' from drabornseries.dbs_series s join drabornseries.dbs_seasons se on se.series_id=s.id and se.number=1 where s.slug='geceye-bir-soz' on conflict(series_id,number) do update set title=excluded.title,description=excluded.description,duration_seconds=excluded.duration_seconds,thumbnail_url=excluded.thumbnail_url,orientation=excluded.orientation,access_type=excluded.access_type,status=excluded.status;
insert into drabornseries.dbs_video_assets(episode_id,provider,demo_url,ready) select e.id,'demo','https://videos.pexels.com/video-files/5909001/5909001-hd_720_1280_24fps.mp4',true from drabornseries.dbs_episodes e join drabornseries.dbs_series s on s.id=e.series_id where s.slug='geceye-bir-soz' and e.number=1 on conflict(episode_id) do update set provider=excluded.provider,demo_url=excluded.demo_url,ready=true;
insert into drabornseries.dbs_episodes(series_id,season_id,number,title,description,duration_seconds,thumbnail_url,orientation,access_type,status) select s.id,se.id,2,'Geceye Bir Söz · Bölüm 2','Lisanslı dikey demo sahnesi. Pexels License · pexels.com/license/ · Katerina Holmes',11,'https://images.pexels.com/videos/5909015/pexels-photo-5909015.jpeg?auto=compress&cs=tinysrgb&w=600','portrait','free','published' from drabornseries.dbs_series s join drabornseries.dbs_seasons se on se.series_id=s.id and se.number=1 where s.slug='geceye-bir-soz' on conflict(series_id,number) do update set title=excluded.title,description=excluded.description,duration_seconds=excluded.duration_seconds,thumbnail_url=excluded.thumbnail_url,orientation=excluded.orientation,access_type=excluded.access_type,status=excluded.status;
insert into drabornseries.dbs_video_assets(episode_id,provider,demo_url,ready) select e.id,'demo','https://videos.pexels.com/video-files/5909015/5909015-hd_720_1280_24fps.mp4',true from drabornseries.dbs_episodes e join drabornseries.dbs_series s on s.id=e.series_id where s.slug='geceye-bir-soz' and e.number=2 on conflict(episode_id) do update set provider=excluded.provider,demo_url=excluded.demo_url,ready=true;
insert into drabornseries.dbs_series(slug,title,short_description,description,genres,accent,poster_url,banner_url,license,status,is_demo,featured_order,total_episodes,average_duration,production_year,age_rating) values('kiyida-ikimiz','Kıyıda İkimiz','Dalgalar, gün batımı ve birlikte atılan bir adım.','Dalgalar, gün batımı ve birlikte atılan bir adım. Bu koleksiyondaki bölümler, 9:16 oynatıcı ve kaydırmalı keşfet deneyimi için lisanslı kısa demo sahneleridir; tamamlanmış bir dizi yapımı değildir.',array['Romantik','Dram']::text[],'#ff9c6c','https://images.pexels.com/videos/9242223/pexels-photo-9242223.jpeg?auto=compress&cs=tinysrgb&w=600','https://images.pexels.com/videos/9242223/pexels-photo-9242223.jpeg?auto=compress&cs=tinysrgb&w=600','Pexels License · pexels.com/license/ · RDNE Stock project','published',true,3,2,12,2026,'13+') on conflict(slug) do update set title=excluded.title,short_description=excluded.short_description,description=excluded.description,genres=excluded.genres,accent=excluded.accent,poster_url=excluded.poster_url,banner_url=excluded.banner_url,license=excluded.license,status=excluded.status,is_demo=excluded.is_demo,featured_order=excluded.featured_order,total_episodes=excluded.total_episodes,average_duration=excluded.average_duration,production_year=excluded.production_year,age_rating=excluded.age_rating;
insert into drabornseries.dbs_seasons(series_id,number,title) select id,1,'İlk bakış' from drabornseries.dbs_series where slug='kiyida-ikimiz' on conflict do nothing;
insert into drabornseries.dbs_episodes(series_id,season_id,number,title,description,duration_seconds,thumbnail_url,orientation,access_type,status) select s.id,se.id,1,'Kıyıda İkimiz · Bölüm 1','Lisanslı dikey demo sahnesi. Pexels License · pexels.com/license/ · RDNE Stock project',10,'https://images.pexels.com/videos/9242223/pexels-photo-9242223.jpeg?auto=compress&cs=tinysrgb&w=600','portrait','free','published' from drabornseries.dbs_series s join drabornseries.dbs_seasons se on se.series_id=s.id and se.number=1 where s.slug='kiyida-ikimiz' on conflict(series_id,number) do update set title=excluded.title,description=excluded.description,duration_seconds=excluded.duration_seconds,thumbnail_url=excluded.thumbnail_url,orientation=excluded.orientation,access_type=excluded.access_type,status=excluded.status;
insert into drabornseries.dbs_video_assets(episode_id,provider,demo_url,ready) select e.id,'demo','https://videos.pexels.com/video-files/9242223/9242223-hd_720_1280_24fps.mp4',true from drabornseries.dbs_episodes e join drabornseries.dbs_series s on s.id=e.series_id where s.slug='kiyida-ikimiz' and e.number=1 on conflict(episode_id) do update set provider=excluded.provider,demo_url=excluded.demo_url,ready=true;
insert into drabornseries.dbs_episodes(series_id,season_id,number,title,description,duration_seconds,thumbnail_url,orientation,access_type,status) select s.id,se.id,2,'Kıyıda İkimiz · Bölüm 2','Lisanslı dikey demo sahnesi. Pexels License · pexels.com/license/ · RDNE Stock project',9,'https://images.pexels.com/videos/9241573/pexels-photo-9241573.jpeg?auto=compress&cs=tinysrgb&w=600','portrait','free','published' from drabornseries.dbs_series s join drabornseries.dbs_seasons se on se.series_id=s.id and se.number=1 where s.slug='kiyida-ikimiz' on conflict(series_id,number) do update set title=excluded.title,description=excluded.description,duration_seconds=excluded.duration_seconds,thumbnail_url=excluded.thumbnail_url,orientation=excluded.orientation,access_type=excluded.access_type,status=excluded.status;
insert into drabornseries.dbs_video_assets(episode_id,provider,demo_url,ready) select e.id,'demo','https://videos.pexels.com/video-files/9241573/9241573-hd_720_1280_24fps.mp4',true from drabornseries.dbs_episodes e join drabornseries.dbs_series s on s.id=e.series_id where s.slug='kiyida-ikimiz' and e.number=2 on conflict(episode_id) do update set provider=excluded.provider,demo_url=excluded.demo_url,ready=true;
insert into drabornseries.dbs_series(slug,title,short_description,description,genres,accent,poster_url,banner_url,license,status,is_demo,featured_order,total_episodes,average_duration,production_year,age_rating) values('ayni-ritim','Aynı Ritim','Kulaklığını tak. Kendi hikâyenin ritmini bul.','Kulaklığını tak. Kendi hikâyenin ritmini bul. Bu koleksiyondaki bölümler, 9:16 oynatıcı ve kaydırmalı keşfet deneyimi için lisanslı kısa demo sahneleridir; tamamlanmış bir dizi yapımı değildir.',array['Müzik']::text[],'#bc73ed','https://images.pexels.com/videos/8003613/pexels-photo-8003613.jpeg?auto=compress&cs=tinysrgb&w=600','https://images.pexels.com/videos/8003613/pexels-photo-8003613.jpeg?auto=compress&cs=tinysrgb&w=600','Pexels License · pexels.com/license/ · Pavel Danilyuk','published',true,4,2,12,2026,'13+') on conflict(slug) do update set title=excluded.title,short_description=excluded.short_description,description=excluded.description,genres=excluded.genres,accent=excluded.accent,poster_url=excluded.poster_url,banner_url=excluded.banner_url,license=excluded.license,status=excluded.status,is_demo=excluded.is_demo,featured_order=excluded.featured_order,total_episodes=excluded.total_episodes,average_duration=excluded.average_duration,production_year=excluded.production_year,age_rating=excluded.age_rating;
insert into drabornseries.dbs_seasons(series_id,number,title) select id,1,'İlk bakış' from drabornseries.dbs_series where slug='ayni-ritim' on conflict do nothing;
insert into drabornseries.dbs_episodes(series_id,season_id,number,title,description,duration_seconds,thumbnail_url,orientation,access_type,status) select s.id,se.id,1,'Aynı Ritim · Bölüm 1','Lisanslı dikey demo sahnesi. Pexels License · pexels.com/license/ · Pavel Danilyuk',13,'https://images.pexels.com/videos/8003613/pexels-photo-8003613.jpeg?auto=compress&cs=tinysrgb&w=600','portrait','free','published' from drabornseries.dbs_series s join drabornseries.dbs_seasons se on se.series_id=s.id and se.number=1 where s.slug='ayni-ritim' on conflict(series_id,number) do update set title=excluded.title,description=excluded.description,duration_seconds=excluded.duration_seconds,thumbnail_url=excluded.thumbnail_url,orientation=excluded.orientation,access_type=excluded.access_type,status=excluded.status;
insert into drabornseries.dbs_video_assets(episode_id,provider,demo_url,ready) select e.id,'demo','https://videos.pexels.com/video-files/8003613/8003613-hd_720_1280_25fps.mp4',true from drabornseries.dbs_episodes e join drabornseries.dbs_series s on s.id=e.series_id where s.slug='ayni-ritim' and e.number=1 on conflict(episode_id) do update set provider=excluded.provider,demo_url=excluded.demo_url,ready=true;
insert into drabornseries.dbs_episodes(series_id,season_id,number,title,description,duration_seconds,thumbnail_url,orientation,access_type,status) select s.id,se.id,2,'Aynı Ritim · Bölüm 2','Lisanslı dikey demo sahnesi. Pexels License · pexels.com/license/ · Pavel Danilyuk',30,'https://images.pexels.com/videos/8005852/pexels-photo-8005852.jpeg?auto=compress&cs=tinysrgb&w=600','portrait','free','published' from drabornseries.dbs_series s join drabornseries.dbs_seasons se on se.series_id=s.id and se.number=1 where s.slug='ayni-ritim' on conflict(series_id,number) do update set title=excluded.title,description=excluded.description,duration_seconds=excluded.duration_seconds,thumbnail_url=excluded.thumbnail_url,orientation=excluded.orientation,access_type=excluded.access_type,status=excluded.status;
insert into drabornseries.dbs_video_assets(episode_id,provider,demo_url,ready) select e.id,'demo','https://videos.pexels.com/video-files/8005852/8005852-hd_720_1280_25fps.mp4',true from drabornseries.dbs_episodes e join drabornseries.dbs_series s on s.id=e.series_id where s.slug='ayni-ritim' and e.number=2 on conflict(episode_id) do update set provider=excluded.provider,demo_url=excluded.demo_url,ready=true;
